---

- name: update all packages
  apt:
    name: '*'
    state: latest

- name: add Docker GPG key
  uri:
    url: https://download.docker.com/linux/ubuntu/gpg 
  ansible.builtin.rpm_key: 
    state: present
    key: /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
  notify:
  - Enable the Docker daemon in systemd
  - Start the Docker daemon
  
- name: Install docker-ce-cli
  apt:
    name: docker-ce-cli
    state: latest

- name: Install containerd.io
  apt:
    name: containerd.io
    state: latest


- name: install epel-release
  apt:
    name: epel-release
    state: latest

# - name: Install yum-utils
#   yum:
#     name: yum-utils
#     state: latest
#   notify:

- name: install python
  apt:
    name: ['python3', 'python3-pip', 'python3-setuptools', 'python-setuptools', 'redhat-rpm-config', 'gcc', 'libffi-devel', 'python3-devel', 'openssl-devel']
    state: latest

- name: update pip
  pip:
    name: pip
    state: latest
    executable: pip3
    extra_args: --upgrade

- name: pip install docker-compose
  pip:
    name: docker-compose
    state: latest
    executable: pip3
    # extra_args: --ignore-installed
  become: true
...