---
- name: update all packages
  apt:
    name: '*'
    state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
  notify:
  - Enable the Docker daemon in systemd
  - Start the Docker daemon
  
- name: Install docker-ce-cli
  apt:
    name: docker-ce-cli
    state: latest

- name: Install containerd.io
  apt:
    name: containerd.io
    state: latest

- name: install python
  apt:
    name: ['python3', 'python3-pip', 'python3-setuptools', 'python-setuptools', 'gcc']
    state: latest

- name: update pip
  pip:
    name: pip
    state: latest
    executable: pip3
    extra_args: --upgrade

- name: pip install docker-compose
  pip:
    name: docker-compose
    state: latest
    executable: pip3
    # extra_args: --ignore-installed
  become: true
...